### ISSUE TITLE
Nist model

### ISSUE THREAD

**Issue by Javi-Rop** [samgoldman97/ms-pred#11]
Dear Repository Team,

I hope this message finds you well. We are pleased to inform you that we hold a NIST license and we are interested in obtaining access to the models trained using the NIST20 library, as mentioned in your repository. We have noticed that you provide download links upon request to users with a NIST license.

We would like to take advantage of this opportunity to access the NIST20 models, as we believe they will be highly valuable for our ongoing projects. Could you please provide us the relevant download links?

We appreciate your collaboration in advance and look forward to getting started with these high-quality resources.

We are at your disposal for any additional information or procedures we need to follow to obtain the download links.

Best regards,

**Comment by samgoldman97** [comment]
Hi Javi

Really appreciate the interest! Can you please send me an email at samlg@mit.edu? Will follow up there and happy to share. Marking as closed. 

Cheers,
Sam
