### ISSUE TITLE
Running on cuda

### ISSUE THREAD

**Issue by taywpd** [samgoldman97/ms-pred#5]
Thank you for the nice model, when I was attempting to run the iceberg_demo notebook on GPU i encountered the following error when attempting to run

outputs = model.predict_mol(smi=test_smiles,
                            adduct=test_ionization,
                            device='cuda:0',
                            max_nodes=100,
                            binned_out=False,
                            threshold=0)

/home/user/mambaforge/envs/ms-gen/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:44: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1631630839582/work/torch/csrc/utils/tensor_numpy.cpp:180.)
  return th.as_tensor(data, dtype=dtype)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_745705/1593813572.py in <cell line: 2>()
      1 # Model predict takes both a smiles string and an ionization
----> 2 outputs = model.predict_mol(smi=test_smiles,
      3                             adduct=test_ionization,
      4                             device='cuda:0',
      5                             max_nodes=100,

~/ms-pred/src/ms_pred/dag_pred/joint_model.py in predict_mol(self, smi, adduct, threshold, device, max_nodes, binned_out)
     86         root_inchi = common.inchi_from_smiles(root_smi)
     87 
---> 88         frag_tree = self.gen_model_obj.predict_mol(
     89             root_smi=root_smi,
     90             adduct=adduct,

~/ms-pred/src/ms_pred/dag_pred/gen_model.py in predict_mol(self, root_smi, adduct, threshold, device, max_nodes)
    460                 broken_nums_tensor = torch.FloatTensor(broken_nums_ar).to(device)
    461 
--> 462                 pred_leaving = self.forward(
    463                     graphs=frag_batch,
    464                     root_repr=root_repr,

~/ms-pred/src/ms_pred/dag_pred/gen_model.py in forward(self, graphs, root_repr, ind_maps, broken, adducts, root_forms, frag_forms)
    199             with root_repr.local_scope():
    200                 if self.embed_adduct:
--> 201                     embed_adducts_expand = embed_adducts.repeat_interleave(
    202                         root_repr.batch_num_nodes(), 0
    203                     )

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument index in method wrapper_index_select)

**Comment by samgoldman97** [comment]
Thanks for your interest! 

1. Did you get it to work on cpu?
2. Did you send the model to gpu before running this? I.e., "`model = model.to(device)`"

**Comment by taywpd** [comment]
Thank you for the quick response!

1. Yes it worked on cpu. However, I noticed it has issues handling heavy atoms such as "Au" and "Sn". Are there limitations on handling certain elements or structures? (i.e. must be a covalently-bonded single molecule, no dimers?) It also resulted in a RuntimeError: CUDA error: device-side assert triggered when running the following molecules:

**Error Molecule 1**
CCCCCCCCCC(=O)N[C@@H](Cc1c[nH]c2ccccc12)C(=O)N[C@H](CC(N)=O)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H]1C(=O)NCC(=O)N[C@@H](CCCN)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@H](C)C(=O)N[C@@H](CC(=O)O)C(=O)NCC(=O)N[C@H](CO)C(=O)N[C@@H]([C@H](C)CC(=O)O)C(=O)N[C@@H](CC(=O)c2ccccc2N)C(=O)O[C@@H]1C

**Error Molecule 2**
CCCCCCCCCCCCC/C=C/[C@@H](O)[C@H](CO[C@@H]1OC(CO)[C@@H](O[C@@H]2OC(CO)[C@H](O[C@@H]3OC(CO)[C@H](O)[C@H](O[C@@H]4OC(CO)[C@H](O)[C@H](O)C4O)C3NC(C)=O)[C@H](O[C@]3(C(=O)O)CC(O)[C@@H](NC(C)=O)C([C@H](O)[C@H](O)CO)O3)C2O)[C@H](O)C1O)NC(=O)CCCCCCCCCCCCCCCCCCC

Then I changed dgl to dgl-cu117 to match my CUDA toolkit version before attempting to run it on GPU.

2. Yes, this is the code I ran

`import pandas as pd
import numpy as np
from collections import defaultdict

import ms_pred.magma.fragmentation as fe
from ms_pred.common.plot_utils import *
from ms_pred.dag_pred import joint_model

set_style()

%load_ext autoreload
%autoreload 2

sample_labels = "../data/spec_datasets/sample_labels.tsv"
test_df = pd.read_csv(sample_labels, sep="\t")

# Get first entry from test_df for smiles and ionization
test_smiles = test_df.iloc[0]['smiles']
test_ionization = test_df.iloc[0]['ionization']

test_smiles = "InChI=1S/C7H15NO3/c1-8(2,3)5-6(9)4-7(10)11/h6,9H,4-5H2,1-3H3/p+1"
test_smiles = "NC(CCCCn1cccc2nc(NCCCC(N)C(=O)O)nc1-2)C(=O)O"
test_ionization = "[M+H]+"

# Get best models
inten_ckpt = f"../quickstart/iceberg/models/canopus_iceberg_score.ckpt"
gen_ckpt = f"../quickstart/iceberg/models/canopus_iceberg_generate.ckpt"

# Load joint model
model = joint_model.JointModel.from_checkpoints(inten_checkpoint=inten_ckpt,
                                                gen_checkpoint=gen_ckpt)

device = "cuda:0"
model = model.to(device)

# Model predict takes both a smiles string and an ionization
outputs = model.predict_mol(smi=test_smiles,
                            adduct=test_ionization,
                            device='cuda:0',
                            max_nodes=100,
                            binned_out=False,
                            threshold=0)`

[08:31:36] WARNING: Omitted undefined stereo

[08:31:36] WARNING: Omitted undefined stereo

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_797579/1593813572.py in <cell line: 2>()
      1 # Model predict takes both a smiles string and an ionization
----> 2 outputs = model.predict_mol(smi=test_smiles,
      3                             adduct=test_ionization,
      4                             device='cuda:0',
      5                             max_nodes=100,

~/ms-pred/src/ms_pred/dag_pred/joint_model.py in predict_mol(self, smi, adduct, threshold, device, max_nodes, binned_out)
     86         root_inchi = common.inchi_from_smiles(root_smi)
     87 
---> 88         frag_tree = self.gen_model_obj.predict_mol(
     89             root_smi=root_smi,
     90             adduct=adduct,

~/ms-pred/src/ms_pred/dag_pred/gen_model.py in predict_mol(self, root_smi, adduct, threshold, device, max_nodes)
    460                 broken_nums_tensor = torch.FloatTensor(broken_nums_ar).to(device)
    461 
--> 462                 pred_leaving = self.forward(
    463                     graphs=frag_batch,
    464                     root_repr=root_repr,

~/ms-pred/src/ms_pred/dag_pred/gen_model.py in forward(self, graphs, root_repr, ind_maps, broken, adducts, root_forms, frag_forms)
    259             root_exp = root_forms[ind_maps]
    260             diffs = root_exp - frag_forms
--> 261             form_encodings = self.embedder(frag_forms)
    262             diff_encodings = self.embedder(diffs)
    263             form_atom_exp = torch.repeat_interleave(form_encodings, exp_num, dim=0)

~/mambaforge/envs/ms-gen/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/ms-pred/src/ms_pred/nn_utils/form_embedder.py in forward(self, tensor)
     44         extra_embeds = self._extra_embeddings[tensor[extra_embed] - self.MAX_COUNT_INT]
     45 
---> 46         out_tensor[~extra_embed] = norm_embeds
     47         out_tensor[extra_embed] = extra_embeds
     48 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Thank you for the recommendation - does it not scale well in GPU?

**Comment by samgoldman97** [comment]
1. Yes, the valid elements (due to ocurence in the training set) are C,N,P,O,S,Si,I,H,Cl,F,Br,B,Se,Fe,Co,As,Na,K (see src/common/chem_utils.py), though it could be extended at some point to use an "unknown" element if you really care about metals I suppose. 
2. We set a maximum mass of 1500 Da, which is likely why those are failing

It scales fine on GPU, but because it's autoregressive prediction and the model is small enough, I find it scales _better_ on CPU at inference parallelized by virtue of how many calculations can be done in parallel (vs. limited GPU memory). Note GPUs for model training is still a necessity. 

That's strange regarding GPU calculations, thank you for flagging. The error is not immediately obvious, so i will need to run this myself when I have some time in the coming days. Since CPU inference works, hopefully that will be sufficient for now. I'm glad you're trying this out-- would be curious to hear if it's helpful for biochemical applications and feel free to shoot us an email.

**Comment by taywpd** [comment]
Thanks for the helpful reply. Is there a way to remove the limit of 1500 Da?

**Comment by samgoldman97** [comment]
It's currently hard coded in the inten_model in the parameter self.inten_buckets (the intensity predictions for all fragments of the same mass are put into the same discretized bin to compute a cosine similarity loss, and we arbitrarily set that to 1500, as that was the cutoff for what the model was trained on). This makes it a little tricky to modify without retraining a model.

You _may_ be able to hack this by changing that parameter after the model is loaded with something like the lines of code below:

```
buckets = torch.DoubleTensor(np.linspace(0, 2500, 25000))
model.inten_model.inten_buckets = buckets
model.inten_model.inten_buckets.requires_grad = False
``` 

But I can't guarantee behavior or be sure this won't mess up anything. If you can get it working with this change, I would also try to do some tests on fragmentation predictions for smaller molecules with the hacked version to make sure they look the same.
