### ISSUE TITLE
Difference between Gen and Inten models

### ISSUE THREAD

**Issue by yuanqidu** [samgoldman97/ms-pred#7]
Dear authors,

May I ask the difference between the base or gen_model vs inten_model for SCARF and ICEBERG?

Best,
Yuanqi

**Comment by samgoldman97** [comment]
Hi Yuanqi, 
Both ICEBERG and SCARF are two part models that work by 1) generating a set of potential peak objects and 2) actually predicting intensities for this larger set of peaks (possibly with some shift). In SCARF, the potential peaks are all subformulae of the input molecule. In ICEBERG, the potential peaks are all substructures of the input molecule. 

The base/gen model is responsible for generating these candidates, whereas the intensity model takes those generated candidates as input and scores them to output a spectrum. The power of this approach is that we do not need to completely enumerate _all_ possible substructures or subformula, as a method like CFM-ID must do, which is one reason why the inference speed is substantially faster. Further, it is memory efficient, which allows all potential peak candidates to be processed by the second "inten" model.

If you read the respective papers and this is still not clear or you have specific questions, I'm happy to describe further!

Best,
Sam

**Comment by yuanqidu** [comment]
Thanks so much for your answer! It is very clear!
